src/accounts/urls.py
from re import template
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from accounts import views as accounts_views
from .views import (
    my_profile,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    profile_view,
    change_password,
)

app_name = "accounts"
urlpatterns = [
    path("", accounts_views.home, name="home"),
    path("register/", accounts_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path(
        "myprofile/",
        my_profile,
        name="my-profile-view",
    ),
    path(
        "my-invites/",
        invites_received_view,
        name="my-invites-view",
    ),
    path(
        "all-profiles/",
        ProfileListView.as_view(),
        name="all-profiles-view",
    ),
    path(
        "to-invite/",
        invite_profiles_list_view,
        name="invite-profiles-view",
    ),
    path("change-password", change_password, name="change_password"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_from_friends, name="remove-friend"),
    path("my-invites/accept/", accept_invitation, name="accept-invite"),
    path("my-invites/reject/", reject_invitation, name="reject-invite"),
    path("u/<slug>/", ProfileDetailView.as_view(), name="profile-detail-view"),
    # new code
    # path('password_reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),name='password_reset_done'),
    # path('password/reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),name='password_reset_complete'),
    #  path('reset_password/',
    #      auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
    #      name="reset_password"),
    #     path('reset_password_sent/',
    #         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
    #         name="password_reset_done"),
    #     path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
    #      name="password_reset_confirm"),
    #     path('reset_password_complete/',
    #         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
    #         name="password_reset_complete"),
    # path('reset_password/',
    #  auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
    #  name="reset_password"),
    # path('reset_password_sent/',
    #     auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
    #     name="password_reset_done"),
    # path('reset/<uidb64>/<token>/',
    #  auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
    #  name="password_reset_confirm"),
    # path('reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
    #     name="password_reset_complete"),
    # path("u/<slug>/", profile_view, name="profile-view"),
    # path("", include("django.contrib.auth.urls")),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # copy
    # path('reset_password/', auth_views.PasswordResetView.as_view(
    #     template_name='accounts/password_reset.html',
    #     # email_template_name='accounts/password_reset_email.html',
    #     # subject_template_name='accounts/password_reset_subject.txt',
    #     success_url=reverse_lazy('accounts:password_reset_done')
    # ), name='reset_password'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
    #     template_name='accounts/password_reset_done.html'
    # ), name='reset_password_sent'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='accounts/password_reset_confirm.html',
    #     success_url=reverse_lazy('accounts:password_reset_complete')
    # ), name='reset_password_confirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
    #     template_name='accounts/password_reset_complete.html'
    # ), name='reset_password_complete'),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            #  email_template_name = 'accounts/reset_password_email.txt',
            success_url=reverse_lazy("accounts:reset_password_sent"),
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_sent.html"
        ),
        name="reset_password_sent",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_form.html",
            success_url=reverse_lazy("accounts:password_reset_confirm"),
        ),
        name="reset_password_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="reset_password_done",
    ),
]

src/item/urls.py
from django.urls import path
from .views import item_detail_view, item_create_view, item_edit_view, item_delete_view

app_name = "item"
urlpatterns = [
    path("view/", item_detail_view, name="item_view"),
    path("<int:id>/view", item_detail_view, name="item_view"),
    path("new/", item_create_view, name="item_create"),
    path("edit/", item_edit_view, name="item_edit"),
    path("<int:id>/edit", item_edit_view, name="item_edit"),
    path("delete/", item_delete_view, name="item_delete"),
    path("<int:id>/delete", item_delete_view, name="item_delete_by_id"),
]

src/silkroad/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from pages.views import home_view, about_view
from accounts import views as accounts_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# from item.views import item_detail_view, item_create_view, item_edit_view, item_delete_view

urlpatterns = [
    path("", home_view, name="home"),
    path("about/", about_view),
    path("admin/", admin.site.urls),
    # My App
    path("item/", include("item.urls")),
    path("", include("accounts.urls")),
    path("", include("contacts.urls")),
    path("", include('django.contrib.auth.urls'))
    
    # Account App
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("image", "first_name", "last_name", "bio")
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "bio": forms.Textarea(attrs={"class": "form-control"}),
        }

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegistrationForm, ProfileModelForm
from .models import Profile, Relationship
from django.views.generic import ListView, DetailView


def home(request):
    return render(request, "accounts/home.html")


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            # obj.first_name = request.user.first_name
            # obj.last_name = request.user.first_name
            obj.save()
            messages.success(
                request, f"Your account has been created. You can log in now!"
            )
            return redirect("/")
    else:
        form = UserRegistrationForm()

    context = {"form": form}
    return render(request, "accounts/register.html", context)


def my_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(
        request.POST or None, request.FILES or None, instance=profile
    )
    confirm = False
    if request.method == "POST":
        if form.is_valid():
            form.save()
            confirm = True
    context = {
        "profile": profile,
        "form": form,
        "confirm": confirm,
    }
    return render(request, "accounts/myprofile.html", context)


def profile_view(request, slug=None):
    # context = {
    #     'title': obj.title,
    #     'description': obj.description,
    #     'price': obj.price,
    #     'name': obj.name
    # }
    if slug:
        obj = Profile.objects.get(user=User.objects.get(username__iexact=slug))
        context = {"object": obj}
        return render(request, "accounts/user_profile_page.html", context)
    # elif "q" in request.GET:
    #     q = request.GET["q"]
    #     # data = Data.objects.filter(last_name__icontains=q)
    #     multiple_q = Q(
    #         Q(title__icontains=q)
    #         | Q(description__icontains=q)
    #         | Q(price__icontains=q)
    #         | Q(name__icontains=q)
    #     )
    #     data = Profile.objects.filter(multiple_q)
    # else:
    #     data = Profile.objects.all()
    # context = {"object": data}
    # return render(request, "accounts/user_profile_page.html", context)


@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {
        "qs": results,
        "is_empty": is_empty,
    }

    return render(request, "accounts/my_invites.html", context)


def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        "qs": qs,
    }
    return render(request, "accounts/to_invite_list.html", context)


def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)
    context = {
        "qs": qs,
    }
    return render(request, "accounts/profile_list.html", context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "accounts/user_profile_page.html"

    # def get_object(self):
    #     slug = self.kwargs.get('slug')
    #     profile = Profile.objects.get(slug=slug)
    #     return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        # context["posts"] = self.get_object().get_all_authors_posts()
        context["len_posts"] = (
            # True if len(self.get_object().get_all_authors_posts()) > 0 else False
        )
        return context


class ProfileListView(ListView):
    model = Profile
    template_name = "accounts/profile_list.html"
    # context_object_name = "qs"

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False
        if len(self.get_queryset()) == 0:
            context["is_empty"] = True

        return context


@login_required
def send_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(
            sender=sender, receiver=receiver, status="send"
        )

        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("accounts:my-profile-view")


@login_required
def remove_from_friends(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver))
            | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("accounts:my-profile-view")


@login_required
def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == "send":
            rel.status = "accepted"
            rel.save()
    return redirect("accounts:my-invites-view")


@login_required
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect("accounts:my-invites-view")


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, "Your password was successfully updated!")
            return redirect("/")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "accounts/change_password.html", {"form": form})


# from .forms import AccountForm
# from .models import Account

# def register(request):
#     context = {}
#     return render(request, 'accounts/register.html', context)

# def login(request):
#     context = {}
#     return render(request, 'accounts/login.html', context)

src/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock content %}

src/accounts/templates/accounts/friendlist.html
<h1>Profile of: {{request.user}}</h1>
{%for friend in profile.get_friends%}
    {{friend}}
    <br>
{%endfor%}
Friends number: {{profile.get_friends_no}}
hello

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<head>
    <div class="center">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login page</title>

    
    <link rel="stylesheet" href="base.html">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,300,0,0" />


    
   
</head>
<body>
   
   <div class="center">
    <div class="login-card-container">  
        <div class="login-card">
            <div class="login-card-logo">   
               
            </div>
            <h1>Sign in</h1>
            <div>please login to use Silkroad</div>
            <h1>
            <form action="" method="POST">
                 {% csrf_token %}
                {% for field in form %}
                <p>{{ field.label }}: <br> {{ field }}</p>
                {% endfor %}        
            
                 
            <div class="form-item-other">
            <div class="checkbox">
                <input type="checkbox" id="RememberMeCheckbox">
                <label for="RemeberMeCheckbox">Remember me</label>
            </div>
            <p><a href="{% url "accounts:reset_password" %}">Forgotten your password?</a></p>  
            </div>
            <h1></h1>
            <button type="submit">Sign In</button>
            </form>
            <div class="login-card-footer">
                Don't have an account? <a href="{% url 'accounts:register' %}">Signup here</a>.
            </div>
        </div>
        
        </div>
    </div>
</div>
</div>
</body>

    <style>
        @import url(reset.css);
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');
  
  body {
    font-family: 'poppins', sans-serif;
    min-height: 100vh;
    background: linear-gradient(to right,#2F3136,#2d3240);
    justify-content: center;  
    align-items: center;
    
  }

  .center {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%); 
  }
  
  .login-card {
      width: 450px;
      background: rgba(255, 255, 255, .5);
      padding: 4rem;
      border-radius: 10px;
      position: relative;
  }
  
  .login-card::before {
      content: '';
      position: absolute;
      background: rgba(255, 255, 255, .15);
      inset: 0;
      transform: rotate(-4deg);
      z-index: -1;
  }
  .login-card-logo {
      margin-bottom: 2rem;
  }
  .login-card-logo img {
      width: 100px;
  }
  
  .login-card-logo,
  .login-card-header,
  .login-card-footer {
      text-align: center;
  }
  .login-card a {
      text-decoration: none;
      color: #fa9e0c;
  }
  .login-card a:hover {
      text-decoration: underline;
  }
  
  .login-card-header {
      margin-bottom: 2rem;
  }
  
  .login-card-header h1 {
      font-size: 2rem;
      font-weight: 600;
      margin-bottom: .5rem;
  }
  
  .login-card-header h1 + div {
      font-size: calc(1rem * .8);
      opacity: .8;
  }
  
  .login-card-form {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
  }
  
  .login-card-form .form-item {
      position: relative;
  }
  
  .login-card-form .form-item .form-item-icon {
      position: absolute;
      top: .82rem;
      left: 1.4rem;
      font-size: 1.3rem;
      opacity: .4;
  }
  
  .login-card-form .checkbox {
      display: flex;
      align-items: center;
      gap: 7px;
  }
  
  .login-card-form .form-item-other {
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: calc(1rem * .8);
      margin-bottom: .5rem;
  }
  
  .login-card-footer {
      margin-top: 1.5rem;
      font-size: calc(1rem * .8);
  }
  .login-card input[type="text"],
  .login-card input[type="password"],
  .login-card input[type="email"] {
      border: none;
      outline: none;
      background: rgba(255, 255, 255, .3);
      padding: 1rem 1.5rem;
      padding-left: calc(1rem * 3.5);
      border-radius: 100px;
      width: 100%;
      transition: background .5s;
  }
  .login-card input:focus {
      background: #2d3240;
  }
  .login-card input[type="checkbox"] {
      width: 16px;
      height: 16px;
      accent-color: #2d3240;
  }
  .login-card button {
      background: #2d3240;
      color: black;
      padding: 1rem;
      border-radius: 100px;
      text-transform: uppercase;
      letter-spacing: 5px;
      transition: background .5s;
  }
  .login-card-form button:hover {
      background-color: rgba(113, 13, 244, 0.85);
      cursor: pointer;
  }
  @media (max-width: 768px) {
    body{
      padding: 2rem 0;
    }
    .login-card {
      width: 300px;
      padding: 2rem;
    }
  }
      </style>
      <style>
           /***
      The new CSS reset - version 1.7.3 (last updated 7.8.2022)
      GitHub page: https://github.com/elad2412/the-new-css-reset
  ***/
  
  /*
      Remove all the styles of the "User-Agent-Stylesheet", except for the 'display' property
      - The "symbol *" part is to solve Firefox SVG sprite bug
   */
   *:where(:not(html, iframe, canvas, img, svg, video, audio):not(svg *, symbol *)) {
      
      display: revert;
  }
  
  /* Preferred box-sizing value */
  *,
  *::before,
  *::after {
      box-sizing: border-box;
  }
  
  /* Reapply the pointer cursor for anchor tags */
  a, button {
      cursor: revert;
  }
  
  /* Remove list styles (bullets/numbers) */
  ol, ul, menu {
      list-style: none;
  }
  
  /* For images to not be able to exceed their container */
  img {
      max-width: 100%;
  }
  
  /* removes spacing between cells in tables */
  table {
      border-collapse: collapse;
  }
  
  /* Safari - solving issue when using user-select:none on the <body> text input doesn't working */
  input, textarea {
      -webkit-user-select: auto;
  }
  
  /* revert the 'white-space' property for textarea elements on Safari */
  textarea {
      white-space: revert;
  }
  
  /* minimum style to allow to style meter element */
  meter {
      -webkit-appearance: revert;
      appearance: revert;
  }
  
  /* reset default text opacity of input placeholder */
  ::placeholder {
      color: unset;
  }
  
  /* fix the feature of 'hidden' attribute.
     display:revert; revert to element instead of attribute */
  :where([hidden]) {
      display: none;
  }
  
  /* revert for bug in Chromium browsers
     - fix for the content editable attribute will work properly.
     - webkit-user-select: auto; added for Safari in case of using user-select:none on wrapper element*/
  :where([contenteditable]:not([contenteditable="false"])) {
      -moz-user-modify: read-write;
      -webkit-user-modify: read-write;
      overflow-wrap: break-word;
      -webkit-line-break: after-white-space;
      -webkit-user-select: auto;
  }
  
  /* apply back the draggable feature - exist only in Chromium and Safari */
  :where([draggable="true"]) {
      -webkit-user-drag: element;
  }
</style>
    



{% endblock %}

src/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="alert alert-success" role="alert">
    <h2 style="text-align: center;">Logged out!</h2>
</div>
{% comment %} 
<h3>Login again?</h3>
<a href="{% url 'accounts:login' %}">---> Login</a> <br>
<a href="{% url 'accounts:home' %}"><--- Or go back to home.</a>
{% endcomment %}

{% endblock %}

src/accounts/templates/accounts/my_invites.html
{% extends 'base.html' %}

{% block content %}

    {% if is_empty %}
        <h1>No invatations here..</h1>
    {% endif %}
 
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</h3>
                        <br>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'accounts:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                         <form action="{% url 'accounts:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

src/accounts/templates/accounts/myprofile.html
{% extends 'base.html' %}

{% block content %}
    <img src={{profile.image.url}} id="profilePic" >
    <div class='form-group' action='{{ action_url }}' enctype='multipart/form-data'>
    <form method='POST' enctype="multipart/form-data"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn btn-success" type="submit" value="Save">
        <a href="/u/{{request.user}}" class="btn btn-primary btn card-links"> View Profile</a>
    
    </form>
    </div>
    




    
    {% comment %} <h1>Profile of: {{profile.user}}</h1>
        <br>
    friend number: {{profile.get_objects_no}}
    hello {% endcomment %}

    <style>
        #profilePic {
            display: block;
            margin-left: 0;
            margin-right: auto;
            height: 120px;
            width: 120px;
            border-radius: 50%;
            object-fit: cover;
        }
        .form-control {
            width: 800px;
        }
    </style>
{% endblock %}

src/accounts/templates/accounts/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{ form.as_p }}
	<input type="Submit" name="Send email">
	
</form>

src/accounts/templates/accounts/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href={% url "accounts:login" %}>Log in</a>

src/accounts/templates/accounts/profile_list.html
{% extends 'base.html' %}

{% block content %}
    All Profiles
    {%if is_empty %}
        <h1>No profiles to interact with</h1>
    {%endif%}
    <ul>
    {%for obj in object_list%}
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column d-flex justify-content-center">
                    <img class="ui small circular image" src={{obj.image.url}} id="all-profile-img">
                </div>
                <div class="thirteen wide column" id="profileButtons">
                    <h3>{{obj.user}}</h3>
                    {% comment %} <p>{{obj.bio}}</p> {% endcomment %}
                    <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>

                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'accounts:send-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="btn btn-success"><i class="bi bi-plus-square"></i> Add to friends</button>
                        </form>
                     {% endif %}

                    {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                    <form>
                        <button type="button" class="btn btn-secondary" disabled><i class="bi bi-plus-square"></i> Waiting for approval</button>
                    </form>
                    {% endif %}

                    {% if request.user in obj.friends.all %}
                    <form action="{% url 'accounts:remove-friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{obj.pk}}>
                        <button type="submit" class="btn btn-danger w-big"><i class="bi bi-dash-square"></i> Remove from friends</button>
                    </form>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
    {%endfor%}
    </ul>
    <style>
        img {
        }
        .three.wide.column {
            align: center;
        }
        .ui {
            background: transparent;
            background-color: #202225;
            border-radius: 8px;
        }
        .ui.segment {
            background: transparent;

        }
        #all-profile-img {
            object-fit: cover;
            height: 150px;
            margin-left: auto;
            margin-right: auto;
        }
        .form
        #profileButtons {
            display: flex;
        }
    </style>
{% endblock %}