src/item/urls.py
from django.urls import path
from .views import item_detail_view, item_create_view, item_edit_view, item_delete_view

app_name = "item"
urlpatterns = [
    path("view/", item_detail_view, name="item_view"),
    path("<int:id>/view", item_detail_view, name="item_view"),
    path("new/", item_create_view, name="item_create"),
    path("edit/", item_edit_view, name="item_edit"),
    path("<int:id>/edit", item_edit_view, name="item_edit"),
    path("delete/", item_delete_view, name="item_delete"),
    path("<int:id>/delete", item_delete_view, name="item_delete_by_id"),
]

src/silkroad/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from pages.views import home_view, about_view
from accounts import views as accounts_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# from item.views import item_detail_view, item_create_view, item_edit_view, item_delete_view

urlpatterns = [
    path("", home_view, name="home"),
    path("about/", about_view),
    path("admin/", admin.site.urls),
    # My App
    path("item/", include("item.urls")),
    path("", include("accounts.urls")),
    path("", include("contacts.urls")),
    path("", include('django.contrib.auth.urls'))
    
    # Account App
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    

src/item/models.py
from turtle import title
from unicodedata import name
from django.db import models
from django.urls import reverse
from accounts.models import Profile

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=1000)
    image = models.ImageField(
        blank=True, null=True, upload_to="marketplace_pics"
    )  # default="default.png"
    name = models.TextField(null=True, blank=True)
    seller = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="seller", null=True, blank=True
    )
    location = models.TextField(null=True, blank=True)
    markAsSold = models.BooleanField()

    def get_absolute_url(self):
        return reverse("item:item_edit", kwargs={"id": self.id})
        # return f"products/{self.id}/"

src/item/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            "image",
            "title",
            "price",
            "description",
            "name",
            "location",
            "markAsSold",
        ]
        exclude = ("name",)
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            # 'description':forms.TextInput(attrs={'class': 'form-control'}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "price": forms.NumberInput(attrs={"class": "form-control"}),
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full Name"}
            ),
            "location": forms.TextInput(attrs={"class": "form-control"}),
            "markAsSold": forms.CheckboxInput(attrs={"class": "form-check"}),
        }

src/item/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.db.models import Q
from django.shortcuts import reverse
from .forms import ItemForm
from .models import Item
from django.contrib.auth.decorators import login_required

from accounts.models import Profile

# Create your views here.
@login_required
def item_create_view(request):
    form = ItemForm(request.POST, request.FILES)
    form_class = ItemForm

    if form.is_valid():
        obj = form.save(commit=False)
        obj.seller = Profile.objects.get(user=request.user)
        obj.name = request.user.get_username()
        obj.save()

    context = {"form": form}
    return render(request, "item/item_create.html", context)


def item_detail_view(request, id=None):
    if id:
        obj = Item.objects.get(id=id)
        context = {"object": obj}
        return render(request, "item/item_detail_inidividual.html", context)
    elif "q" in request.GET:
        q = request.GET["q"]
        multiple_q = Q(
            Q(title__icontains=q)
            | Q(description__icontains=q)
            | Q(price__icontains=q)
            | Q(name__icontains=q)
        )
        data = Item.objects.filter(multiple_q)
    else:
        data = Item.objects.all().order_by("-id")
    context = {"object": data}
    return render(request, "item/item_detail.html", context)


@login_required
def item_edit_view(request, id=None):
    if id:
        item = Item.objects.get(id=id)
        form = ItemForm(request.POST or None, request.FILES or None, instance=item)
        confirm = False
        print("my id is: ", item.title)
        if request.method == "POST":
            if form.is_valid():
                form.save()
                confirm = True
        context = {
            "item": item,
            "form": form,
            "confirm": confirm,
        }
        return render(request, "item/item_edit_individual.html", context)
    else:
        obj = Item.objects.all().order_by("-id")
        context = {"object": obj}
        return render(request, "item/item_edit.html", context)


@login_required
def item_delete_view(request, id=None):
    if id and request.method == "POST":
        objSingle = Item.objects.get(id=id)
        objSingle.delete()
        return redirect(reverse("item:item_view"))
    elif id:
        obj = Item.objects.get(id=id)
        print("")
        context = {"object": obj}
        return render(request, "item/item_delete_confirm.html", context)
    else:
        obj = Item.objects.all().order_by("-id")
        context = {"object": obj}
        return render(request, "item/item_delete.html", context)

src/item/templates/item/item_create.html
{% extends 'base.html' %}

{% block content %}
<div class='form-group' action='{{ action_url }}' enctype='multipart/form-data'>
<form method='POST' enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-lg btn-success" type="submit" value="Publish">

</form>
</div>
<style>
    .form-group {
        padding: 0 300px;
    }
</style>
{% endblock %}

src/item/templates/item/item_delete.html
{% extends 'base.html' %}

{% block content %}



<h1>Delete - from the item app</h1>
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Name</th>
        <th scope="col">Confirm Delete</th>
        <th scope="col">Quick Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for i in object %}
        <tr>
            <th scope="row">{{ i.id }}</th>
            <td>{{i.title}}</td>
            <td>{{i.description}}</td>
            <td>{{i.price}}</td>
            <td>{{i.name}}</td>
            <td><a class="btn btn-sm btn-outline-danger" href="{% url 'item:item_delete_by_id' i.id %}">Delete</a></td>
            <form action="{% url 'item:item_delete_by_id' i.id %}" method="POST">
                {% csrf_token %}
            <td><input class="btn btn-sm btn-outline-danger" type="submit" value="Delete"></td>
            </form>
            
            
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock %}

src/item/templates/item/item_delete_confirm.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
      
    <div id="products" class="row">
        <div class="item col">
            <div class="thumbnail">
              
                <img class="group list-group-image" src={% if object.image %}{{object.image.url}}{%else%}"https://source.unsplash.com/400x250/?mobile"{% endif %} alt="" />
                <div class="caption">
                    {%if request.user == object.seller.user%}
                      <h1>Are you sure you want to delete?</h1>
                      <form action="{% url 'item:item_delete_by_id' object.id %}" method="POST">
                        {% csrf_token %}
                        <a href={% url 'item:item_delete' %}Cancel</a>
                        <input class="btn btn-outline-danger" type="submit" value="Delete">

                      </form>
                    {%endif%}
                    <h2>Name: {{object.title}}</h2>
                    <h3>₱ {{object.price}}</h3>
                    <p class="itemtext fw-lighter lh-base">Location: {{object.location}}</p>
                    <p class="itemtext fw-lighter lh-base">Description: {{object.description|linebreaks}}</p>
                    <p class="itemtext fw-lighter lh-base">Seller:</p>
                    <a href={{object.seller.get_absolute_url}}>
                    <button type="button" id="sellerButton" class="btn btn-secondary text-start btn-lg fs-5 fw-normal" data-bs-toggle="popover" data-bs-placement="left">
                      <div class="seller-profile">
                        <img class="seller-avatar" src={{object.seller.image.url}}>
                        <div class="seller-details">
                          {{object.seller.first_name}} {{object.seller.last_name}}<br>
                          {{object.seller.user}}
                        </div>
                      </div>
                    </button>
                    </a>
                </div>
            </div>
          
        </div>
    </div>
  </div>

  <style>
    .seller-profile {
      display: flex;
    }
    
    .seller-avatar {
      height: 48px;
      width: 48px;
      border-radius: 50%; 
    }
    #sellerButton {
      width: 300px;
    }
    .thumbnail {
      display: flex;
      gap: 30px;
    }
    .marketplace-header {
      display: flex;
      gap: 10px;
    }
    .middle {
      {% comment %} background-color: #18191A; {% endcomment %}
      padding: 0px;
    }
    .caption {
      padding-top: 7px;
    }
    .itemtext {
      margin: 0px;
    }
    img.group {
      width: 750px;
      height: 850px;
      border-radius: 8px;
      border: 1px solid #202122;
    }
  div.item {
    margin: 4px;
    height: 850px;
  }
  .form-control {
    width: 340px;
  }

  </style>
{% endblock %}

src/item/templates/item/item_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    
    <h1>Silk Road Marketplace</h1>
    <div class="marketplace-header">
    <form action="{% url 'item:item_view' %}" method="get">
      <input name="q" type="text" placeholder="Search..." class="form-control">
    </form>
    <br>
      <a href="{% url "item:item_create" %}"><button class="btn btn-success bi-bi-basket" type="submit"><i class="bi bi-basket"></i> Create Listing</button></a>
      <a href="{% url "item:item_edit" %}"><button class="btn btn-primary" type="submit"><i class="bi bi-pencil-square"></i> Edit item</button></a>
      <a href="{% url "item:item_delete" %}"><button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Delete item</button></a>
    </div>
      <br>
    <strong>Display</strong>
      <div class="btn-group">
          <a href="#" id="list" class="btn btn-default btn-sm"> <span class="bi bi-list-ul"></span> List</a> 
          <a href="#" id="grid" class="btn btn-default btn-sm"> <span class="bi bi-grid-3x3-gap-fill"></span> Grid</a>
      </div>
  <div id="products" class="row">
    {% for i in object %}
      <div class="item col">
        <a href="/item/{{i.id}}/view">
          <div class="thumbnail">
            
              <img class="group list-group-image" src={% if i.image %}{{i.image.url}}{%else%}"https://source.unsplash.com/400x250/?mobile"{% endif %} alt="" />
              <div class="caption">
                  <p class="itemtext fs-5 fw-semibold" id="price">₱ {{i.price}}</p>
                  <p class="itemtext fw-normal">{{i.title}}</p>
                  <p class="itemtext fw-lighter lh-base">{{i.location}}</p>
              </div>
          </div>
        </a> 
         
      </div>
    {% endfor %}
  </div>
</div>

  <style>
    .marketplace-header {
      display: flex;
      gap: 10px;
    }
    .middle {
      {% comment %} background-color: #18191A; {% endcomment %}
      padding: 0px;
    }
    .caption {
      padding-top: 7px;
    }
    .itemtext {
      margin: 0px;
    }
    img.group {
      width: 277px;
      height: 277px;
      border-radius: 8px;
      border: 1px solid #202122;
    }
  div.item {
    margin: 4px;
    max-width: 277px;
    height: 379px;
  }
  .form-control {
    width: 340px;
  }

  </style>
{% endblock %}

src/item/templates/item/item_detail_inidividual.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
      
    <div id="products" class="row">
        <div class="item col">
            <div class="thumbnail">
              
                <img class="group list-group-image" src={% if object.image %}{{object.image.url}}{%else%}"https://source.unsplash.com/400x250/?mobile"{% endif %} alt="" />
                <div class="caption">
                    {%if request.user == object.seller.user%}
                    <div class="marketplace-header">
                      <a href="{{object.get_absolute_url}}"><button class="btn btn-primary" type="submit"><i class="bi bi-pencil-square"></i> Edit item</button></a>
                      <a href="{% url 'item:item_delete_by_id' object.id %}"><button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Delete item</button></a>
                    </div>
                    {%endif%}
                    <h2>Name: {{object.title}}</h2>
                    <h3>₱ {{object.price}}</h3>
                    <p class="itemtext fw-lighter lh-base">Location: {{object.location}}</p>
                    <p class="itemtext fw-lighter lh-base">Description: {{object.description|linebreaks}}</p>
                    <p class="itemtext fw-lighter lh-base">Seller:</p>
                    <a href={{object.seller.get_absolute_url}}>
                    <button type="button" id="sellerButton" class="btn btn-secondary text-start btn-lg fs-5 fw-normal" data-bs-toggle="popover" data-bs-placement="left">
                      <div class="seller-profile">
                        <img class="seller-avatar" src={{object.seller.image.url}}>
                        <div class="seller-details">
                          {{object.seller.first_name}} {{object.seller.last_name}}<br>
                          {{object.seller.user}}
                        </div>
                      </div>
                    </button>
                    </a>
                </div>
            </div>
          
        </div>
    </div>
  </div>

  <style>
    .seller-profile {
      display: flex;
    }
    
    .seller-avatar {
      height: 48px;
      width: 48px;
      border-radius: 50%; 
      object-fit: cover;
      margin-right: 10px;
    }
    #sellerButton {
      width: 300px;
    }
    .thumbnail {
      display: flex;
      gap: 30px;
    }
    .marketplace-header {
      display: flex;
      gap: 10px;
    }
    .middle {
      {% comment %} background-color: #18191A; {% endcomment %}
      padding: 0px;
    }
    .caption {
      padding-top: 7px;
    }
    .itemtext {
      margin: 0px;
    }
    img.group {
      width: 750px;
      height: 850px;
      border-radius: 8px;
      border: 1px solid #202122;
    }
  div.item {
    margin: 4px;
    height: 850px;
  }
  .form-control {
    width: 340px;
  }

  </style>
{% endblock %}

src/item/templates/item/item_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Items - from the item app</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Name</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        {% for i in object %}
        <tr>
                {% csrf_token %}
                <th scope="row">{{i.id}}</th>
                <td class="editable" data-id="{{ i.id }}" data-type="title">{{i.title}}</td>
                <td class="editable" data-id="{{ i.id }}" data-type="description">{{i.description}}</td>
                <td class="editable" data-id="{{ i.id }}" data-type="price">{{i.price}}</td>  
                <td class="editable" data-id="{{ i.id }}" data-type="name">{{i.name}}</td>
                {% comment %} <td><input class="btn btn-sm btn-outline-danger" type="submit" value="Edit"></td> {% endcomment %}
                <td><a href="{{i.get_absolute_url}}" class="btn btn-secondary btn-xs card-links">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block extrascripts %}
    <script>
        console.log("Hello world!");
        $(document).ready(function(){
            $(document).on("dblclick",".editable",function(){
                var value=$(this).text();
                var input="<input type='"+input_type+"' class='input-data' value='"+value+"' class='form-control'>";
                $(this).html(input);
                $(this).removeClass("editable")
            });
        });
    </script>
{% endblock %}

src/item/templates/item/item_edit_individual copy.html
{% extends 'base.html' %}

{% block content %}
<h1>Individual View</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col">Available</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{object.id}}</th>
            <td>{{object.title}}</td>
            <td>{{object.description}}</td>
            <td>{{object.price}}</td>
            <td>{{object.name}}</td>
            <td>{{object.location}}</td>
            <td>
              {% if object.markAsSold == True %}
                ✔️
              {% else %}
                ❌
              {% endif %}
            </td>
        </tr>
    </tbody>
  </table>
{% endblock %}

src/item/templates/item/item_edit_individual.html
{% extends 'base.html' %}

{% block content %}
<div class='form-group' action='{{ action_url }}' enctype='multipart/form-data'>
<form method='POST' enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn btn-success" type="submit" value="Edit Listing">

</form>
</div>
<style>
    .form-group {
        padding: 0 300px;
    }
</style>
{% endblock %}